Imports Telerik.Web.UI
Imports System.Net.Mail
Imports System.Data.SqlClient
Imports System.IO

Public Class job_application
    Inherits System.Web.UI.UserControl
    'Dim webPartManager As WebPartManager
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        If Not IsPostBack Then
            If Not Request.QueryString("jid") Is Nothing Then
                ddlposition.SelectedValue = Request.QueryString("jid").ToString
            End If
        End If
    End Sub
    Protected Sub btnapply_Click(sender As Object, e As EventArgs) Handles btnapply.Click
        Dim sqlinsert As String
        Dim cls As New clscode
        Dim name As String = txtname.Text.Trim
        Dim email As String = txtemail.Text.Trim
        Dim phone As String = txtphone.Text.Trim
        Dim jobid As Int32 = ddlposition.SelectedItem.Value
        Dim jobposition As String = ddlposition.SelectedItem.Text
        Dim targetFileName As String = String.Empty
        Dim targetfolder As String = Server.MapPath("~/Modules/careers/attachments/")
        Dim filepath As String = String.Empty
        If AsyncUpload1.UploadedFiles.Count > 0 Then
            Dim fileattach As UploadedFile = AsyncUpload1.UploadedFiles(0)
            If (System.IO.File.Exists(targetfolder + fileattach.FileName)) Then
                targetFileName = GetFilename(fileattach, targetfolder)
            Else
                targetFileName = fileattach.FileName.ToString
            End If
            filepath = System.IO.Path.Combine(targetfolder, targetFileName)
            fileattach.SaveAs(filepath, False)
        End If
        sqlinsert = "INSERT INTO job_applications (name,mail,phone,attachment, job_positionid,datesubmitted) values "
        sqlinsert += "('" & name & "','" & email & "','" & phone & "','" & targetFileName & "'," & jobid & ",getdate())"
        cls.ExecNonQuery(sqlinsert)

        Dim msg As String = String.Empty
        Dim msgplain As String = String.Empty

        Dim sendto As String = ""
        Dim subject As String = ""
        Dim dr As SqlDataReader
        dr = cls.ExecReader("Select notification_subject,notification_sendto from notifications where notification_code='JA' and notification_isnotify='True'")
        If dr.HasRows Then
            dr.Read()
            sendto = dr("notification_sendto")
            subject = dr("notification_subject")
            Using reader As StreamReader = New StreamReader(Server.MapPath("~/webparts/careers/emailbody.html"))
                msg = reader.ReadToEnd
            End Using
            msg = msg.Replace("{Position}", jobposition)
            msg = msg.Replace("{Name}", name)
            msg = msg.Replace("{Email}", email)
            msg = msg.Replace("{Phone}", phone)
            msgplain = "New Job Application \r\n Positon: " & jobposition & "\nFrom: " & name & "Email: " & email & "\nPhone: " & phone
            Dim attach As New Attachment(filepath)
            cls.Send(name, email, sendto.Substring(0, sendto.IndexOf("@")), sendto, subject, msg, msgplain, attach)
        End If
        dr.Close()


        'sendto = cls.ExecScalar("Select notification_sendto from notifications where notification_code='JA' and notification_isnotify='True'")
        'msg = "<span style='font-size:20px'>New Job Application</span><br><br><b>From:</b>&nbsp;" & name & "<br><b>Email:</b>&nbsp;" & email & "<br><b>Phone Number:</b>&nbsp;" & phone & "<br><br><br><i>Note: This is an autogenerated email, please do not reply.</i><hr/>"
        'Dim attach As New Attachment(Server.MapPath("~/Modules/careers/attachments/" & targetFileName))
        'cls.Send(name, email, sendto.Substring(0, sendto.IndexOf("@")), sendto, "Job Application", msg, msg, attach)


        If Not Request.QueryString("jid") Is Nothing Then
            Response.Redirect("~/webparts/careers/thankyou.aspx?t=jap")
        Else
            Response.Redirect("~/webpages/thankyou.aspx?t=jap")
        End If
    End Sub

    Function GetFilename(UploadedFile As UploadedFile, targetFolder As String) As String

        Dim counter As Integer = 1
        Dim file As UploadedFile = UploadedFile
        Dim targetFileName As String = file.GetNameWithoutExtension() + counter.ToString() + file.GetExtension()
        While (System.IO.File.Exists(System.IO.Path.Combine(targetFolder, targetFileName)))
            counter = counter + 1
            targetFileName = file.GetNameWithoutExtension() + counter.ToString() + file.GetExtension()
        End While

        Return targetFileName

    End Function


End Class